2025-01-27 15:56:03,894 - INFO - chatbot_2.py:100 - Device selected: cpu
2025-01-27 15:56:03,904 - INFO - chatbot_2.py:237 - Application started.
2025-01-27 15:56:03,950 - INFO - chatbot_2.py:110 - Ollama model initialized successfully.
2025-01-27 15:56:11,932 - INFO - SentenceTransformer.py:218 - Load pretrained SentenceTransformer: sentence-transformers/all-mpnet-base-v2
2025-01-27 15:56:11,934 - DEBUG - connectionpool.py:1049 - Starting new HTTPS connection (1): huggingface.co:443
2025-01-27 15:56:12,198 - DEBUG - connectionpool.py:544 - https://huggingface.co:443 "HEAD /sentence-transformers/all-mpnet-base-v2/resolve/main/modules.json HTTP/1.1" 200 0
2025-01-27 15:56:12,412 - DEBUG - connectionpool.py:544 - https://huggingface.co:443 "HEAD /sentence-transformers/all-mpnet-base-v2/resolve/main/config_sentence_transformers.json HTTP/1.1" 200 0
2025-01-27 15:56:12,684 - DEBUG - connectionpool.py:544 - https://huggingface.co:443 "HEAD /sentence-transformers/all-mpnet-base-v2/resolve/main/README.md HTTP/1.1" 200 0
2025-01-27 15:56:12,897 - DEBUG - connectionpool.py:544 - https://huggingface.co:443 "HEAD /sentence-transformers/all-mpnet-base-v2/resolve/main/modules.json HTTP/1.1" 200 0
2025-01-27 15:56:13,101 - DEBUG - connectionpool.py:544 - https://huggingface.co:443 "HEAD /sentence-transformers/all-mpnet-base-v2/resolve/main/sentence_bert_config.json HTTP/1.1" 200 0
2025-01-27 15:56:13,325 - DEBUG - connectionpool.py:544 - https://huggingface.co:443 "HEAD /sentence-transformers/all-mpnet-base-v2/resolve/main/adapter_config.json HTTP/1.1" 404 0
2025-01-27 15:56:13,542 - DEBUG - connectionpool.py:544 - https://huggingface.co:443 "HEAD /sentence-transformers/all-mpnet-base-v2/resolve/main/config.json HTTP/1.1" 200 0
2025-01-27 15:56:14,345 - DEBUG - connectionpool.py:544 - https://huggingface.co:443 "HEAD /sentence-transformers/all-mpnet-base-v2/resolve/main/tokenizer_config.json HTTP/1.1" 200 0
2025-01-27 15:56:14,639 - DEBUG - connectionpool.py:544 - https://huggingface.co:443 "GET /api/models/sentence-transformers/all-mpnet-base-v2/revision/main HTTP/1.1" 200 6777
2025-01-27 15:56:14,862 - DEBUG - connectionpool.py:544 - https://huggingface.co:443 "GET /api/models/sentence-transformers/all-mpnet-base-v2 HTTP/1.1" 200 6777
2025-01-27 15:56:14,869 - INFO - chatbot_2.py:121 - Embedding function loaded successfully.
2025-01-27 15:56:14,873 - DEBUG - loader.py:62 - Environment variable FAISS_OPT_LEVEL is not set, so let's pick the instruction set according to the current CPU
2025-01-27 15:56:14,873 - INFO - loader.py:74 - Loading faiss with AVX512 support.
2025-01-27 15:56:14,873 - INFO - loader.py:79 - Could not load library with AVX512 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx512'")
2025-01-27 15:56:14,873 - INFO - loader.py:86 - Loading faiss with AVX2 support.
2025-01-27 15:56:15,182 - INFO - loader.py:88 - Successfully loaded faiss with AVX2 support.
2025-01-27 15:56:15,190 - CRITICAL - chatbot_2.py:133 - Failed to load FAISS index 'db': Error in __cdecl faiss::FileIOReader::FileIOReader(const char *) at D:\a\faiss-wheels\faiss-wheels\faiss\faiss\impl\io.cpp:68: Error: 'f' failed: could not open faiss_index\index.faiss for reading: No such file or directory
2025-02-17 10:17:39,773 - INFO - chatbot_2.py:101 - Device selected: cpu
2025-02-17 10:17:39,773 - INFO - chatbot_2.py:114 - Loading Ollama model: llama3:instruct...
2025-02-17 10:17:39,786 - INFO - chatbot_2.py:117 - Ollama model initialized successfully.
2025-02-17 10:17:43,067 - INFO - SentenceTransformer.py:218 - Load pretrained SentenceTransformer: sentence-transformers/all-mpnet-base-v2
2025-02-17 10:17:43,067 - DEBUG - connectionpool.py:1049 - Starting new HTTPS connection (1): huggingface.co:443
2025-02-17 10:17:44,121 - DEBUG - connectionpool.py:544 - https://huggingface.co:443 "HEAD /sentence-transformers/all-mpnet-base-v2/resolve/main/modules.json HTTP/1.1" 200 0
2025-02-17 10:17:44,787 - DEBUG - connectionpool.py:544 - https://huggingface.co:443 "HEAD /sentence-transformers/all-mpnet-base-v2/resolve/main/config_sentence_transformers.json HTTP/1.1" 200 0
2025-02-17 10:17:45,011 - DEBUG - connectionpool.py:544 - https://huggingface.co:443 "HEAD /sentence-transformers/all-mpnet-base-v2/resolve/main/README.md HTTP/1.1" 200 0
2025-02-17 10:17:45,230 - DEBUG - connectionpool.py:544 - https://huggingface.co:443 "HEAD /sentence-transformers/all-mpnet-base-v2/resolve/main/modules.json HTTP/1.1" 200 0
2025-02-17 10:17:45,444 - DEBUG - connectionpool.py:544 - https://huggingface.co:443 "HEAD /sentence-transformers/all-mpnet-base-v2/resolve/main/sentence_bert_config.json HTTP/1.1" 200 0
2025-02-17 10:17:46,045 - DEBUG - connectionpool.py:544 - https://huggingface.co:443 "HEAD /sentence-transformers/all-mpnet-base-v2/resolve/main/adapter_config.json HTTP/1.1" 404 0
2025-02-17 10:17:46,266 - DEBUG - connectionpool.py:544 - https://huggingface.co:443 "HEAD /sentence-transformers/all-mpnet-base-v2/resolve/main/config.json HTTP/1.1" 200 0
2025-02-17 10:17:48,418 - DEBUG - connectionpool.py:544 - https://huggingface.co:443 "HEAD /sentence-transformers/all-mpnet-base-v2/resolve/main/tokenizer_config.json HTTP/1.1" 200 0
2025-02-17 10:17:48,818 - DEBUG - connectionpool.py:544 - https://huggingface.co:443 "GET /api/models/sentence-transformers/all-mpnet-base-v2/revision/main HTTP/1.1" 200 6803
2025-02-17 10:17:49,673 - DEBUG - connectionpool.py:544 - https://huggingface.co:443 "GET /api/models/sentence-transformers/all-mpnet-base-v2 HTTP/1.1" 200 6803
2025-02-17 10:17:49,689 - INFO - chatbot_2.py:134 - Embedding function loaded successfully.
2025-02-17 10:17:49,690 - DEBUG - loader.py:62 - Environment variable FAISS_OPT_LEVEL is not set, so let's pick the instruction set according to the current CPU
2025-02-17 10:17:49,690 - INFO - loader.py:74 - Loading faiss with AVX512 support.
2025-02-17 10:17:49,696 - INFO - loader.py:79 - Could not load library with AVX512 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx512'")
2025-02-17 10:17:49,696 - INFO - loader.py:86 - Loading faiss with AVX2 support.
2025-02-17 10:17:49,718 - INFO - loader.py:88 - Successfully loaded faiss with AVX2 support.
2025-02-17 10:17:49,735 - CRITICAL - chatbot_2.py:151 - Failed to load FAISS index 'db': Error in __cdecl faiss::FileIOReader::FileIOReader(const char *) at D:\a\faiss-wheels\faiss-wheels\faiss\faiss\impl\io.cpp:68: Error: 'f' failed: could not open faiss_index\index.faiss for reading: No such file or directory
2025-02-27 16:24:35,632 - INFO - chatbot_2.py:101 - Device selected: cpu
2025-02-27 16:24:35,632 - INFO - chatbot_2.py:114 - Loading Ollama model: llama3:instruct...
2025-02-27 16:24:35,641 - INFO - chatbot_2.py:117 - Ollama model initialized successfully.
2025-02-27 16:24:55,034 - INFO - chatbot_2.py:394 - Application started.
2025-02-27 16:24:58,275 - INFO - SentenceTransformer.py:218 - Load pretrained SentenceTransformer: sentence-transformers/all-mpnet-base-v2
2025-02-27 16:24:58,275 - DEBUG - connectionpool.py:1049 - Starting new HTTPS connection (1): huggingface.co:443
2025-02-27 16:24:58,289 - DEBUG - connectionpool.py:1049 - Starting new HTTPS connection (2): huggingface.co:443
2025-02-27 16:24:58,297 - DEBUG - connectionpool.py:1049 - Starting new HTTPS connection (3): huggingface.co:443
2025-02-27 16:24:58,301 - DEBUG - connectionpool.py:1049 - Starting new HTTPS connection (4): huggingface.co:443
2025-02-27 16:24:58,301 - DEBUG - connectionpool.py:1049 - Starting new HTTPS connection (5): huggingface.co:443
2025-02-27 16:24:58,314 - DEBUG - connectionpool.py:1049 - Starting new HTTPS connection (6): huggingface.co:443
2025-02-27 16:24:58,320 - DEBUG - connectionpool.py:1049 - Starting new HTTPS connection (7): huggingface.co:443
2025-02-27 16:24:58,919 - DEBUG - connectionpool.py:1049 - Starting new HTTPS connection (8): huggingface.co:443
2025-02-27 16:24:58,944 - DEBUG - connectionpool.py:1049 - Starting new HTTPS connection (9): huggingface.co:443
2025-02-27 16:24:58,962 - DEBUG - connectionpool.py:1049 - Starting new HTTPS connection (10): huggingface.co:443
2025-02-27 16:24:58,972 - INFO - chatbot_2.py:134 - Embedding function loaded successfully.
2025-02-27 16:24:58,972 - DEBUG - loader.py:62 - Environment variable FAISS_OPT_LEVEL is not set, so let's pick the instruction set according to the current CPU
2025-02-27 16:24:58,972 - INFO - loader.py:74 - Loading faiss with AVX512 support.
2025-02-27 16:24:58,972 - INFO - loader.py:79 - Could not load library with AVX512 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx512'")
2025-02-27 16:24:58,972 - INFO - loader.py:86 - Loading faiss with AVX2 support.
2025-02-27 16:24:58,991 - INFO - loader.py:88 - Successfully loaded faiss with AVX2 support.
2025-02-27 16:24:59,007 - CRITICAL - chatbot_2.py:151 - Failed to load FAISS index 'db': Error in __cdecl faiss::FileIOReader::FileIOReader(const char *) at D:\a\faiss-wheels\faiss-wheels\faiss\faiss\impl\io.cpp:68: Error: 'f' failed: could not open faiss_index\index.faiss for reading: No such file or directory
